### ISSUE TITLE
Doubt about Pro and Pro Plus H54x - 200 motors

### ISSUE THREAD

**Issue by aqvale** [ROBOTIS-GIT/dynamixel-workbench#314]
Hi,

We are using 3 Dynamixels H54-200 PRO and 1 Dynamixel H54P-100 and 1 Dynamixel H54P-020, but we can't get Dynamixel workbench to communicate with them all in the same network. 

We are using Protocol 2.0, all motors with firmware v44 and U2D2.

Is there any compatibility issue? Or some trick to get them working together?

Best regards,

**Comment by ROBOTIS-Will** [comment]
Hi @aqvale 
I'm sorry about the delayed response on your issue.
Before running the code, make sure that each DYNAMIXEL has different ID so that their packets do not collide each other.
Also, it is recommended to test DYNAMIXEL using [DYNAMIXEL Wizard 2.0](https://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/) before running with an example code.
Please feel free to reach to us if you have any difficulties in using DYNAMIXEL.
Thank you.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't recent activity. Please feel free to reopen when necessary.
